# Simplified Cloud Build Configuration
# Focuses on core Firebase deployment without complex GCE integration

steps:
  # Step 1: Install Firebase CLI
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔧 Installing Firebase CLI..."
        npm install -g firebase-tools
        firebase --version
        echo "✅ Firebase CLI installed"

  # Step 2: Install Functions dependencies and build
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Installing Functions dependencies..."
        cd functions
        npm install
        echo "🔨 Building Functions..."
        npm run build
        echo "✅ Functions built successfully"

  # Step 3: Deploy Firestore Rules and Indexes
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📊 Deploying Firestore configuration..."
        if [ -n "${_FIREBASE_TOKEN}" ]; then
          firebase deploy --only firestore:rules,firestore:indexes --project $PROJECT_ID --token ${_FIREBASE_TOKEN}
        else
          echo "Using default service account for Firestore deployment"
          firebase deploy --only firestore:rules,firestore:indexes --project $PROJECT_ID
        fi
        echo "✅ Firestore configuration deployed"

  # Step 4: Deploy Functions
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying Firebase Functions..."
        if [ -n "${_FIREBASE_TOKEN}" ]; then
          firebase deploy --only functions --project $PROJECT_ID --token ${_FIREBASE_TOKEN}
        else
          echo "Using default service account for Functions deployment"
          firebase deploy --only functions --project $PROJECT_ID
        fi
        echo "✅ Firebase Functions deployed"

  # Step 5: Deploy App Hosting (if configured)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🌐 Deploying App Hosting..."
        if [ -n "${_FIREBASE_TOKEN}" ]; then
          firebase deploy --only apphosting --project $PROJECT_ID --token ${_FIREBASE_TOKEN}
        else
          echo "Using default service account for App Hosting deployment"
          firebase deploy --only apphosting --project $PROJECT_ID
        fi
        echo "✅ App Hosting deployed"

# Build configuration
timeout: '1800s'  # 30 minutes

# Substitutions
substitutions:
  _FIREBASE_TOKEN: ''  # Optional: Set in Cloud Build trigger

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_4'  # Reduced from 8 to 4 for cost optimization
  diskSizeGb: 50