# Cloud Build Configuration
# Automatically deploys Firebase Functions when code is pushed to Git
# Firebase will run this automatically when connected to your repository

steps:
  # Step 1: Install Firebase CLI
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '-g', 'firebase-tools']

  # Step 2: Install Functions dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    dir: 'functions'
    args: ['install']

  # Step 3: Build Functions (TypeScript)
  - name: 'node:20'
    entrypoint: 'npm'
    dir: 'functions'
    args: ['run', 'build']

  # Step 4: Deploy Functions
  - name: 'node:20'
    entrypoint: 'npx'
    args: [
      'firebase-tools',
      'deploy',
      '--only', 'functions',
      '--project', '$PROJECT_ID',
      '--token', '${_FIREBASE_TOKEN}'
    ]
    env:
      - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}'

# Set timeout for build
timeout: '1800s'

# Substitutions
substitutions:
  _FIREBASE_TOKEN: ''  # Will be set by Firebase automatically

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

