# Cloud Build Configuration
# Automatically deploys Firebase components when code is pushed to Git
# Firebase will run this automatically when connected to your repository

steps:
  # Step 1: Install Firebase CLI
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '-g', 'firebase-tools']

  # Step 2: Deploy Firestore Rules (if changed)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📊 Deploying Firestore Rules and Indexes..."
        if [ -n "${_FIREBASE_TOKEN}" ]; then
          npx firebase-tools deploy --only firestore:rules,firestore:indexes --project $PROJECT_ID --token ${_FIREBASE_TOKEN}
        else
          echo "⚠️ No Firebase token provided, using default service account"
          npx firebase-tools deploy --only firestore:rules,firestore:indexes --project $PROJECT_ID
        fi
        echo "✅ Firestore configuration deployed"

  # Step 3: Install Functions dependencies
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Installing Functions dependencies..."
        cd functions
        npm install
        echo "✅ Functions dependencies installed"

  # Step 4: Build Functions (TypeScript)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔨 Building Functions..."
        cd functions
        npm run build
        echo "✅ Functions built successfully"

  # Step 5: Deploy Functions
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying Firebase Functions..."
        if [ -n "${_FIREBASE_TOKEN}" ]; then
          npx firebase-tools deploy --only functions --project $PROJECT_ID --token ${_FIREBASE_TOKEN}
        else
          echo "⚠️ No Firebase token provided, using default service account"
          npx firebase-tools deploy --only functions --project $PROJECT_ID
        fi
        echo "✅ Firebase Functions deployed"

# Set timeout for build
timeout: '1800s'

# Substitutions
substitutions:
  _FIREBASE_TOKEN: ''  # Will be set by Cloud Build trigger or use default service account

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

