/**
 * Comprehensive WISP Equipment Categories
 * Used across inventory, planning, and deployment modules
 */

export const equipmentCategories = {
  'EPC Equipment': [
    'Distributed EPC Server',
    'HSS (Home Subscriber Server)',
    'MME (Mobility Management Entity)',
    'S-GW (Serving Gateway)',
    'P-GW (Packet Data Network Gateway)',
    'PCRF (Policy and Charging Rules Function)',
    'SMF (Session Management Function)',
    'AMF (Access and Mobility Management Function)',
    'UPF (User Plane Function)',
    'N3IWF (Non-3GPP Interworking Function)',
    'EPC Core Network Appliance',
    'LTE Core Server',
    '5G Core Server'
  ],
  'Radio Equipment': [
    'Base Station (eNodeB/gNodeB)',
    'Remote Radio Head (RRH)',
    'Radio Unit (RU)',
    'Baseband Unit (BBU)',
    'Distributed Unit (DU)',
    'Centralized Unit (CU)',
    'Small Cell',
    'Femtocell',
    'Picocell',
    'Microcell',
    'Repeater',
    'Amplifier',
    'RF Amplifier',
    'PA (Power Amplifier)',
    'LNA (Low Noise Amplifier)',
    'Microwave Radio',
    'Point-to-Point Radio',
    'Point-to-Multipoint Radio',
    'CBRS CBSD (Citizens Broadband Radio Service Device)',
    'LTE Base Station',
    '5G Base Station',
    'WiFi Access Point (Outdoor)',
    'WiFi Access Point (Indoor)',
    'WiMAX Base Station',
    'Fixed Wireless Access (FWA) Radio',
    'PTP (Point-to-Point) Bridge',
    'PTMP (Point-to-Multipoint) AP',
    'Subscriber Module (SM)',
    'Subscriber Unit (SU)'
  ],
  'Antennas': [
    'Sector Antenna',
    'Panel Antenna',
    'Omni Antenna',
    'Parabolic Dish Antenna',
    'Grid Antenna',
    'Flat Panel Antenna',
    'Yagi Antenna',
    'MIMO Antenna',
    'Massive MIMO Array',
    '4x4 MIMO Antenna',
    '8x8 MIMO Antenna',
    'Dual-Polarized Antenna',
    'GPS Antenna',
    'GLONASS Antenna',
    'Timing Antenna',
    'Antenna Combiner',
    'Antenna Splitter',
    'Diplexer',
    'Duplexer',
    'RF Coupler',
    'RF Splitter',
    'RF Combiner',
    'Passive Intermodulation (PIM) Test Port'
  ],
  'Power Systems': [
    'AC to DC Rectifier',
    'DC Power Supply',
    '48V DC Power Supply',
    '24V DC Power Supply',
    '12V DC Power Supply',
    'Battery Bank',
    'Lead-Acid Battery',
    'Lithium-Ion Battery',
    'Gel Battery',
    'UPS (Uninterruptible Power Supply)',
    'Backup Generator',
    'Solar Panel System',
    'Solar Panel',
    'Solar Charge Controller',
    'Wind Turbine',
    'Fuel Cell',
    'Power Distribution Unit (PDU)',
    'DC Power Plant',
    'AC Power Distribution',
    'DC Power Distribution',
    'Surge Protector',
    'Lightning Arrestor',
    'Ground Fault Circuit Interrupter (GFCI)',
    'Power Over Ethernet (PoE) Injector',
    'PoE Splitter',
    'PoE Switch',
    'Power Inverter',
    'DC to AC Converter',
    'Voltage Regulator',
    'Power Meter',
    'Load Bank'
  ],
  'Networking Equipment': [
    'Core Router',
    'Edge Router',
    'Access Router',
    'Wireless Router',
    'Layer 2 Switch',
    'Layer 3 Switch',
    'Managed Switch',
    'Unmanaged Switch',
    'Gigabit Switch',
    '10 Gigabit Switch',
    '25 Gigabit Switch',
    '100 Gigabit Switch',
    'PoE Switch',
    'Stackable Switch',
    'Firewall',
    'Next-Generation Firewall (NGFW)',
    'Load Balancer',
    'Load Balancing Router',
    'Optical Network Terminal (ONT)',
    'Optical Network Unit (ONU)',
    'Media Converter',
    'Fiber to Ethernet Converter',
    'Ethernet to Fiber Converter',
    'Copper to Fiber Media Converter',
    'Network Tap',
    'Packet Capture Device',
    'Network Analyzer',
    'Bandwidth Manager',
    'QoS (Quality of Service) Device',
    'Traffic Shaper',
    'Network Time Server (NTP)',
    'DHCP Server',
    'DNS Server',
    'RADIUS Server',
    'AAA Server'
  ],
  'Transmission Equipment': [
    'Fiber Optic Terminal',
    'OLT (Optical Line Terminal)',
    'ODN (Optical Distribution Network)',
    'Fiber Distribution Hub',
    'Fiber Distribution Panel',
    'Fiber Optic Patch Panel',
    'Fiber Optic Enclosure',
    'Splice Closure',
    'Fiber Optic Adapter Panel',
    'Multiplexer (DWDM)',
    'Multiplexer (CWDM)',
    'Demultiplexer',
    'Optical Add-Drop Multiplexer (OADM)',
    'Reconfigurable OADM (ROADM)',
    'Optical Amplifier',
    'EDFA (Erbium-Doped Fiber Amplifier)',
    'Optical Transponder',
    'Transceiver (SFP/SFP+/QSFP)',
    'SFP Module',
    'SFP+ Module',
    'QSFP Module',
    'QSFP28 Module',
    'XFP Module',
    'Coaxial Cable',
    'RG6 Coaxial Cable',
    'RG11 Coaxial Cable',
    'LMR Coaxial Cable',
    'Fiber Optic Cable',
    'Single-Mode Fiber (SMF)',
    'Multi-Mode Fiber (MMF)',
    'Hybrid Fiber-Coaxial (HFC) Cable',
    'RF Cable',
    'RF Jumper Cable',
    'RF Coaxial Jumper',
    'Low-Loss Coaxial Cable',
    'Semi-Rigid Coaxial Cable',
    'Waveguide',
    'Rectangular Waveguide',
    'Circular Waveguide',
    'Fiber Optic Connector',
    'LC Connector',
    'SC Connector',
    'ST Connector',
    'FC Connector',
    'MPO Connector',
    'Coaxial Connector',
    'N-Type Connector',
    'SMA Connector',
    'TNC Connector',
    'BNC Connector',
    'F-Type Connector'
  ],
  'Environmental Control': [
    'HVAC Unit',
    'Air Conditioner',
    'Split System AC',
    'Packaged AC Unit',
    'Heat Pump',
    'Heat Exchanger',
    'Ventilation Fan',
    'Exhaust Fan',
    'Circulation Fan',
    'Heater',
    'Space Heater',
    'Dehumidifier',
    'Humidifier',
    'Temperature Sensor',
    'Humidity Sensor',
    'Environmental Monitoring System',
    'Fire Suppression System',
    'Fire Detection System',
    'Smoke Detector',
    'Heat Detector',
    'Flame Detector',
    'Gas Detection System',
    'Vibration Sensor',
    'Door Contact Sensor'
  ],
  'Monitoring & Control': [
    'Remote Monitoring Unit (RMU)',
    'Remote Terminal Unit (RTU)',
    'SNMP Agent',
    'SNMP Manager',
    'Network Management System (NMS)',
    'Element Management System (EMS)',
    'GPS Clock',
    'GPS Timing Source',
    'NTP Server',
    'Stratum 1 Time Server',
    'CCTV Camera',
    'IP Camera',
    'PTZ Camera',
    'Dome Camera',
    'Bullet Camera',
    'Thermal Camera',
    'Night Vision Camera',
    'Video Recorder (DVR/NVR)',
    'Access Control System',
    'Card Reader',
    'Biometric Reader',
    'Keypad',
    'Electronic Lock',
    'Alarm Panel',
    'Intrusion Detection System',
    'Motion Sensor',
    'Door/Window Sensor',
    'Glass Break Sensor',
    'Siren/Horn',
    'Strobe Light',
    'Environmental Alert System',
    'Power Monitoring Device',
    'Current Monitor',
    'Voltage Monitor'
  ],
  'Structural & Housing': [
    'Equipment Shelter',
    'Prefabricated Shelter',
    'Equipment Cabin',
    'Equipment Cabinet',
    '19" Rack',
    '23" Rack',
    'Wall-Mount Rack',
    'Open Frame Rack',
    'Enclosed Rack',
    'Rack Mount Kit',
    'Rack Shelf',
    'Rack Drawer',
    'Rack Blanking Panel',
    'Cable Management Panel',
    'Vertical Cable Manager',
    'Horizontal Cable Manager',
    'Weatherproof Enclosure',
    'Outdoor Enclosure',
    'NEMA Enclosure',
    'IP65 Enclosure',
    'IP67 Enclosure',
    'Fiber Optic Enclosure',
    'Underground Enclosure',
    'Pedestal Enclosure',
    'Cable Tray',
    'Cable Ladder',
    'Cable Raceway',
    'Cable Duct',
    'Cable Conduit',
    'Tower Lighting System',
    'Obstruction Light',
    'Aircraft Warning Light',
    'Beacon Light',
    'Navigation Light',
    'Lightning Protection System',
    'Grounding System',
    'Ground Rod',
    'Grounding Wire',
    'Bonding Strap',
    'Lightning Arrestor',
    'Surge Arrestor',
    'Gas Discharge Tube',
    'TVSS (Transient Voltage Surge Suppressor)',
    'Tower Mount',
    'Pole Mount',
    'Wall Mount',
    'Roof Mount',
    'Mast Mount',
    'Antenna Mount',
    'Tilt Mount',
    'Azimuth Mount'
  ],
  'Test Equipment': [
    'Spectrum Analyzer',
    'Vector Signal Analyzer',
    'Network Analyzer',
    'Cable Tester',
    'TDR (Time Domain Reflectometer)',
    'OTDR (Optical Time Domain Reflectometer)',
    'Power Meter',
    'Optical Power Meter',
    'RF Power Meter',
    'VSWR Meter',
    'Return Loss Meter',
    'Insertion Loss Meter',
    'Multimeter',
    'Digital Multimeter',
    'Clamp Meter',
    'Megohmmeter',
    'Signal Generator',
    'RF Signal Generator',
    'Function Generator',
    'Oscilloscope',
    'Digital Oscilloscope',
    'Protocol Analyzer',
    'Packet Capture Device',
    'Network Tester',
    'Ethernet Tester',
    'Fiber Tester',
    'Fiber Identifier',
    'Fiber Scope',
    'PIM Tester (Passive Intermodulation)',
    'Antenna Analyzer',
    'Site Master',
    'GPS Simulator',
    'BER Tester (Bit Error Rate)',
    'Throughput Tester',
    'Latency Tester',
    'Jitter Tester',
    'Temperature Probe',
    'Hygrometer',
    'Anemometer',
    'Light Meter'
  ],
  'CPE Devices': [
    'LTE CPE',
    '5G CPE',
    'CBRS CPE',
    'Fixed Wireless CPE',
    'Point-to-Point CPE',
    'Point-to-Multipoint CPE',
    'Subscriber Unit (SU)',
    'Subscriber Module (SM)',
    'Customer Premises Equipment',
    'Outdoor Unit (ODU)',
    'Indoor Unit (IDU)',
    'Integrated CPE',
    'Split-Mount CPE',
    'Cable Modem',
    'DOCSIS Modem',
    'ONT (Optical Network Terminal)',
    'ONU (Optical Network Unit)',
    'WiFi Router',
    'Wireless Router',
    'Mesh Router',
    'WiFi Access Point',
    'WiFi Extender',
    'WiFi Repeater',
    'Ethernet Adapter',
    'USB Adapter',
    'Powerline Adapter',
    'MoCA Adapter',
    'Gigabit Ethernet Adapter',
    'Customer Modem',
    'Residential Gateway',
    'Home Gateway',
    'Voice Gateway',
    'Video Gateway'
  ],
  'SIM Cards': [
    'SIM Card (Physical)',
    'SIM Card (Embedded)',
    'eSIM Profile',
    'M2M SIM Card',
    'IoT SIM Card',
    'UICC Card',
    'SIM Card Programmer',
    'SIM Card Reader'
  ],
  'Cables & Accessories': [
    'Ethernet Cable',
    'Cat5e Cable',
    'Cat6 Cable',
    'Cat6a Cable',
    'Cat7 Cable',
    'Cat8 Cable',
    'Fiber Patch Cable',
    'Fiber Optic Patch Cord',
    'LC-LC Patch Cable',
    'SC-SC Patch Cable',
    'LC-SC Patch Cable',
    'MPO-MPO Cable',
    'RF Jumper Cable',
    'RF Coaxial Jumper',
    'N-N Jumper',
    'SMA-SMA Jumper',
    'BNC-BNC Jumper',
    'RF Connector',
    'N-Type Connector',
    'SMA Connector',
    'TNC Connector',
    'BNC Connector',
    'F-Type Connector',
    '7/16 DIN Connector',
    'Adapter',
    'N to SMA Adapter',
    'N to TNC Adapter',
    'Gender Changer',
    'Attenuator',
    'RF Attenuator',
    'Fixed Attenuator',
    'Variable Attenuator',
    'Terminator',
    'RF Terminator',
    'Load',
    'Dummy Load',
    'RF Load',
    'Filter',
    'Bandpass Filter',
    'Bandstop Filter',
    'Low-Pass Filter',
    'High-Pass Filter',
    'Diplexer',
    'Triplexer',
    'Coupler',
    'Directional Coupler',
    'Splitter',
    'Power Splitter',
    'Combiner',
    'Power Combiner',
    'Isolator',
    'Circulator',
    'Amplifier',
    'Preamplifier',
    'Bias Tee',
    'DC Block',
    'Lightning Arrestor',
    'Gas Discharge Tube',
    'Fuse Holder',
    'Fuse',
    'Circuit Breaker',
    'Power Connector',
    'Power Cord',
    'Extension Cord',
    'Power Strip',
    'Surge Protector Strip',
    'Cable Tie',
    'Velcro Tie',
    'Cable Label',
    'Heat Shrink Tubing',
    'Electrical Tape',
    'Wire Nut',
    'Crimp Connector',
    'Lug Connector'
  ],
  'Tools': [
    'Drill',
    'Hammer Drill',
    'Impact Driver',
    'Drill Bit Set',
    'Concrete Bit',
    'Masonry Bit',
    'Crimper',
    'Coaxial Crimper',
    'Ethernet Crimper',
    'Fiber Crimper',
    'Cable Stripper',
    'Coaxial Stripper',
    'Fiber Stripper',
    'Wire Stripper',
    'Torque Wrench',
    'Digital Torque Wrench',
    'Socket Set',
    'Wrench Set',
    'Screwdriver Set',
    'Hex Key Set',
    'Allen Wrench Set',
    'Ladder',
    'Extension Ladder',
    'Step Ladder',
    'Scaffolding',
    'Safety Harness',
    'Climbing Gear',
    'Hoist',
    'Come Along',
    'Ratchet Strap',
    'Measuring Tape',
    'Laser Level',
    'Spirit Level',
    'Multimeter',
    'Voltage Tester',
    'Cable Tester',
    'Tone Generator',
    'Cable Toner',
    'Cable Locator',
    'Ground Rod Driver',
    'Sledgehammer',
    'Post Hole Digger',
    'Shovel',
    'Pick',
    'Crowbar',
    'Pry Bar',
    'Utility Knife',
    'Wire Cutters',
    'Diagonal Cutters',
    'Lineman Pliers',
    'Needle Nose Pliers',
    'Channel Lock Pliers',
    'Vise Grip',
    'Adjustable Wrench',
    'Pipe Wrench',
    'Hacksaw',
    'Reciprocating Saw',
    'Circular Saw',
    'Angle Grinder',
    'Heat Gun',
    'Soldering Iron',
    'Solder',
    'Flux',
    'Heat Shrink Gun',
    'Fiber Cleaver',
    'Fiber Splicer',
    'Fusion Splicer',
    'Mechanical Splicer',
    'Fiber Polishing Kit',
    'Fiber Inspection Scope',
    'OTDR',
    'Power Meter',
    'VSWR Meter',
    'Spectrum Analyzer',
    'Site Master',
    'GPS Unit',
    'Compass',
    'Binoculars',
    'Telescope',
    'Telescoping Mast',
    'Pull String',
    'Fish Tape',
    'Wire Fish',
    'Cable Lube',
    'Conduit Bender',
    'Conduit Reamer',
    'Tap and Die Set',
    'Threading Die',
    'Pipe Threader',
    'Vacuum Cleaner',
    'Shop Vac',
    'Air Compressor',
    'Blow Gun',
    'Safety Equipment',
    'Hard Hat',
    'Safety Glasses',
    'Safety Gloves',
    'Work Boots',
    'Reflective Vest',
    'Hearing Protection',
    'Dust Mask',
    'Respirator'
  ],
  'Spare Parts': [
    'Power Supply',
    'AC Power Supply',
    'DC Power Supply',
    '48V Power Supply',
    '24V Power Supply',
    '12V Power Supply',
    'Fan Module',
    'Cooling Fan',
    'Exhaust Fan',
    'Fan Filter',
    'Transceiver',
    'SFP Transceiver',
    'SFP+ Transceiver',
    'QSFP Transceiver',
    'XFP Transceiver',
    'Filter',
    'RF Filter',
    'Bandpass Filter',
    'Low-Pass Filter',
    'High-Pass Filter',
    'Duplex Filter',
    'Cable Assembly',
    'RF Cable Assembly',
    'Fiber Cable Assembly',
    'Ethernet Cable Assembly',
    'Connector',
    'RF Connector',
    'Fiber Connector',
    'Ethernet Connector',
    'Adapter',
    'Gender Changer',
    'Mounting Bracket',
    'Antenna Mount',
    'Rack Mount Kit',
    'Wall Mount Kit',
    'Fuse',
    'Circuit Breaker',
    'Relay',
    'LED Indicator',
    'LCD Display',
    'Keypad',
    'Button',
    'Switch',
    'Resistor',
    'Capacitor',
    'Inductor',
    'Diode',
    'Transistor',
    'IC (Integrated Circuit)',
    'O-Ring',
    'Gasket',
    'Seal',
    'Weather Seal',
    'Heat Shrink',
    'Cable Tie',
    'Screw',
    'Bolt',
    'Nut',
    'Washer',
    'Lock Washer',
    'Cotter Pin',
    'Retaining Ring',
    'Snap Ring',
    'Grease',
    'Lubricant',
    'Contact Cleaner',
    'Dielectric Grease',
    'Thermal Paste',
    'Thread Lock',
    'Silicone Sealant',
    'Cable Gland',
    'Strain Relief',
    'Cable Clamp',
    'Grommet',
    'Bushing'
  ],
  'Other': [
    'Miscellaneous Equipment',
    'Custom Equipment',
    'Unknown Equipment'
  ]
};

export const categoryList = Object.keys(equipmentCategories);

export function getEquipmentTypesByCategory(category: string): string[] {
  return equipmentCategories[category as keyof typeof equipmentCategories] || [];
}

export function getAllEquipmentTypes(): string[] {
  return Object.values(equipmentCategories).flat();
}

